apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    spinnaker: spinnaker-halyard
  name: halyard
  namespace: spinnaker
spec:
  serviceAccountName: spinnaker-user-dev
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      spinnaker: spinnaker-halyard
  template:
    metadata:
      labels:
        spinnaker: spinnaker-halyard
    spec:
      containers:
      - image: halyard:stable
        imagePullPolicy: Always
        name: halyard
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
